- name: Cambiar contrase単a
  hosts: all
  become: yes
  vars_prompt:
    - name: username
      prompt: "Introduce el nombre del usuario al que cambiar la contrase単a"
      private: no
    - name: password
      prompt: "Introduce la contrase単a nueva del usuario"
      private: yes

  tasks:
    - name: Cambio de contrase単a
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"