- name: Insertar nombre usuario
  hosts: all
  become: yes
  vars_prompt:
    - name: username
      prompt: "Introduzca el nombre de usuario que quieres que sea sudo"
  tasks:
    - name: adding existing user '{{ username }}' to group sudo
      user:
        name: '{{ username }}'
        groups: sudo
        append: yes
